In [12]:
import pandas as pd
import numpy as np

In [13]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns=["Column1","Column2","Column3","Column4"])

In [18]:
df.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [19]:
df.to_csv('Test1')

In [22]:
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [23]:
type(df.loc['Row1'])

pandas.Series

In [24]:
df.iloc[:,:]

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [25]:
df.iloc[0:2,0:2]

      Column1  Column2
Row1        0        1
Row2        4        5